language: scala
sudo: false
scala:
- 2.12.12
jdk:
- openjdk8
before_install:
- openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv
  -in all.gpg.enc -out all.gpg -d
- bash scripts/setEnvironment.sh;
install:
- if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/install.sh; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/install.sh; fi
- if [ "$TRAVIS_BRANCH" != "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then sbt
  ++$TRAVIS_SCALA_VERSION test; fi
script:
- if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishSnapshot.sh; fi
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishRelease.sh; fi
after_success:
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash
  scripts/publishDoc.sh; fi
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt"
  - "$HOME/.cache/coursier"
env:
  global:
    secure: uRMKxXOYIR932xdR2MhUn50CqJwqfdu7oUZEOXrGoBuyylN1u/DKDgbnme0rfJoh11uXBGT35EEZIXLrWrxg3Qt2xw130QFYgIjGpofTeSeDNNlpaGgB7VCC2N3Ck3fANKI9OjH7dDlMr2FW8NFl3u6cuRO68Tvm9MqEc4765Mi//2ybdHPpvCB1SjqIgcB58uwIpl/+ohKhWY+AQ/JSMdgR0jKurwIEITUVtxZcO1gj4HcCeVdPOO+0AhwtNhWnyRTqJFYYg6ErhqjsRxwmQod1Ky3SsNFH/vYYzPfgCzekvKiS42mm8kLiYM2ZtTnYHMZzeuavup9rKq8LLDH/sUo3wUMI7D99OylVjcVSIBedFjtMCDvIY/alTt1zbJPgy+G/yzwnTfy8JY79/2j41xgMHKYKk0k/FpFyrSYCr/x37/AgIaTOJhq36ON0yvSBEPOIj4Pc1EZXHXbpM8i2YmgFRt8VBt6HpAymzX7Z0ZY3MsDXxeQ9rGd/0uSrb7pUU6X8+gSPWxura8eO6t+X71F6dt8A41/dlL7GTzQYBZoX850W+QBfuqjDIf1w75P7J4ey8jbiaLslQ7/YxYqMpcjPRdXscfreitvw7tZu7hpQ00kG9T5bvmLXlF2x40bqxOOBtw5y6azvPksEeDFxm84gZG/W0gRlV4TUaetD5xs=
