language: scala
sudo: false
scala:
  - 2.12.12
jdk:
  - openjdk8

cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt"
    - "$HOME/.cache/coursier"

script:
  - sbt +test scalafmtCheckAll scalafmtSbtCheck;
