language: scala
sudo: false
scala:
  - 2.12.10
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier

before_install:
  - export SONATYPE_USER=$SONATYPE_USER
  - export SONATYPE_PASSWORD=$SONATYPE_PASSWORD
  - export GITHUB_TOKEN=$GITHUB_TOKEN

install:
  - bash scripts/install.sh;

script:
  - sbt test
#  - sbt release

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
