language: scala
sudo: false
scala:
  - 2.12.10
jdk:
  - openjdk8

before_install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/decrypt-keys.sh; fi

install:
  - bash scripts/install.sh;

script:
  - sbt test
#  - sbt release

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then bash scripts/publishMicrosite.sh; fi
