language: scala
sudo: false
scala:
  - 2.12.10
jdk:
  - openjdk8

cache:
  directories:
    - $HOME/.m2
    - $HOME/.ivy2/cache
    - $HOME/.sbt
    - $HOME/.cache/coursier
    - $HOME/.gnupg

before_install:
  - openssl aes-256-cbc -K $encrypted_404964577bd1_key -iv $encrypted_404964577bd1_iv -in all.gpg.enc -out all.gpg -d
  - bash scripts/setEnvironment.sh;

install:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false"]; then
    bash scripts/installGnupg.sh;
    bash scripts/install.sh;
    elif [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/installGnupg.sh;
    bash scripts/install.sh;
    else
    sbt ++$TRAVIS_SCALA_VERSION test;
    fi

script:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/publishRelease.sh;
    elif [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/publishSnapshot.sh;
    fi

after_success:
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then
    bash scripts/publishDoc.sh;
    fi
